### ISSUE TITLE
Koppeling met online gegevensbronnen

### ISSUE THREAD

**Issue by valdemetriades** [ArtesiaWater/UGW#2]
- RWS data is verplaatst
- HDSR-koppeling geeft een onduidelijke foutmelding. Mogelijk is er iets in de naamgeving veranderd.

**Comment by dbrakenhoff** [comment]
When running `01_merge_sources.py` I'm getting the following response for WSRL which results in a `KeyError` when attempting to access `'maxRecordCount'`:

`{'error': {'code': 500, 'message': 'Service Kaarten/Vigerend_Peilgebieden/MapServer not found ', 'details': []}}`

The url is `'https://kaarten.wsrl.nl/arcgis/rest/services/Kaarten/Vigerend_Peilgebieden/MapServer'`

**Comment by dbrakenhoff** [comment]
The new url should be: `https://kaarten.wsrl.nl/arcgis/rest/services/Kaarten/Peilgebieden_vigerend/MapServer`
Also streefpeil attribute is now called STREEFPEIL

**Comment by dbrakenhoff** [comment]
I'm was able to run the `01_merge_sources.py` script, but I'm missing the `water_lines.shp` file after completion. The logger also indicates some errors reading a V&V source:
```
WARNING:root:source for RWS not specified in water_lines
INFO:root:water_lines V&V
WARNING:root:reading ESRI-json format (GeoJSON is preferred)
ERROR:root:Processing data from the following url failed: https://services1.arcgis.com/ug8NBKcLHVNmdmdt/ArcGIS/rest/services/Legger_Watersysteem/FeatureServer/15/?f=pjson
ERROR:root:ArcREST Layer has no Unique ID Field, script defaulted to None.Please specify a correct object_id for this layer & adminstration
```

**Comment by d2hydro** [comment]
Compared to the original delivery, I changed the following in the sources.json:
- source for water-level_areas Rivierenland: service url & attributes changed:
 - services.rivierenland_peilvakken.url: https://kaarten.wsrl.nl/arcgis/rest/services/Kaarten/Vigerend_Peilgebieden/MapServer -> https://kaarten.wsrl.nl/arcgis/rest/services/Kaarten/Peilgebieden_vigerend/MapServer
 - water-level_areas.Rivierenland.attributes: made all attributs compatible with fields @ https://kaarten.wsrl.nl/arcgis/rest/services/Kaarten/Peilgebieden_vigerend/MapServer/0
- source-specs water-lines adjusted: layer numbers changed and attributes dissapeared :-(
 - water_lines.V&V.layers.layers: [14, 15, 16] -> [16, 17, 18] (layers changed)
 - water_lines.V&V.layers.attributes: removed all attributes as new layers do not contain these info any more :-(
- attributes for waternet water_lines changed
 - water_lines.Waternet.attributes: changed to meet new attribute-ids.
- layer name for water-level_areas RWS:
 - water-level_areas.RWS.layer: kaderrichtlijn_water:oppervlaktewater_lichamen_v
 
Where V&V had attributes in their legger defining water cross-sections it is gone. As a result, the input-files for MODFLOW will be of less quality. Especially lacking bottom level info is a miss.

**Comment by JJansen-rhdhv** [comment]
Seems to work now for the whole UGW extent.
For a smaller extent there is an issue with at least one of the online sources.

Error messages:

INFO:root:water_lines HDSR
ERROR:root:Processing data from the following url failed: https://services1.arcgis.com/1lWKHMyUIR3eKHKD/ArcGIS/rest/services/HydroObjecten/FeatureServer/0/query?where=OBJECTID>=0&geometry=142466.1116914851,466994.8487679956,143122.50046358033,467591.157388806&geometryType=esriGeometryEnvelope&f=json&inSR=28992&returnIdsOnly=true with error local variable 'gdf' referenced before assignment
Traceback (most recent call last):
  File "01_merge_sources.py", line 412, in <module>
    gdf, gdf_invalid = get_layer(src_layer, admins_gdf)
  File "01_merge_sources.py", line 258, in get_layer
    layer, poly, object_filter=object_filter, object_id=object_id)
  File "D:\UGW_GitHubDesktop\UGW\scripts\oppervlaktewater\services.py", line 190, in get_features
    raise e
  File "D:\UGW_GitHubDesktop\UGW\scripts\oppervlaktewater\services.py", line 173, in get_features
    if not gdf.empty:
UnboundLocalError: local variable 'gdf' referenced before assignment

**Comment by dbrakenhoff** [comment]
@JJansen-rhdhv could you send us the extent? That way we can reproduce the issue locally.

**Comment by JJansen-rhdhv** [comment]
I think it was this extent (see attached shapefile)
[Extent_small.zip](https://github.com/ArtesiaWater/UGW/files/7666956/Extent_small.zip)
.

**Comment by d2hydro** [comment]
I reproduced it and fixed it with a new services.py. @JJansen-rhdhv; can you test if it works?
